stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/amazon_alexa.tsv
    outs:
      - data/raw.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw.csv
      - config/params.yaml
    outs:
      - data/processed.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed.csv
      - config/params.yaml
    outs:
      - models/countVectorizer.pkl
      - models/scaler.pkl

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - models/countVectorizer.pkl
      - models/scaler.pkl
      - data/processed.csv
      - config/params.yaml
    outs:
      - models/model_xgb.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model_xgb.pkl
      - data/processed.csv
